#! /bin/bash
PKG=com.radio_sensors.rs
ACTION=Client
APP=Client-debug.apk

function run()
{ 
 ant clean debug 
 adb install bin/$APP
 adb shell am start -n $PKG/$PKG.$ACTION
}

function remove()
{
 adb uninstall $PKG
}

function log()
{
#    Log.d ("t1", "t2"); in App
    adb logcat 
#    adb logcat RStrace:D *:S; for only RStrace debug
}

function init_project()
{
# Generate local.properties file
    android update project -p .
}

function update_project()
{ 
    android update project --subprojects -p $HOME/workspace/RS --target 1
}

function sign()
{
    ant clean release
    jarsigner -verbose -keystore RS.keystore bin/Client-release-unsigned.apk RS
    rm -f Read-Sensors.apk 
    zipalign 4 bin/Client-release-unsigned.apk Read-Sensors.apk
}

function make_key()
{
#CN=Robert Olsson, OU=RD, O=Radio Sensors AB, L=Uppsala, ST=Unknown, C=SE
    keytool -genkey -v -keystore RS.keystore -alias RS -keyalg RSA -validity 10000
}

function debug_over_ip()
{
    # Get IP address ov android
    adb tcpip 5555
    adb connect 192.168.2.91:5555
    # Disconnect USB cable
    adb logcat
}

function screenshot()
{
    adb shell screencap -p /sdcard/screen.png
    adb pull /sdcard/screen.png
}



remove
run




